// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzyvxpntujlowqxarooc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6eXZ4cG50dWpsb3dxeGFyb29jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MTgyMjcsImV4cCI6MjA1NjA5NDIyN30.Y6tx-y3USS4cLWezsT8o8-kzI7gCg7KMFQKEOadoEf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);